=== ptII/ptII/ptolemy/moml/MoML_1.dtd
<!-- MoML DTD Version 1.4, UC Berkeley -->
<!-- $Id$ -->
<!-- If you update this file, please also update:  -->
<!--    ptweb/xml/dtd/MoML_1.dtd, -->
<!--    ptII/doc/design/src/MoML.fm, -->
<!--    the static field MoML_DTD_1 in MoMLParser.java. -->
<!-- The top-level element can be either model or class. -->
<!-- NOTE: To ensure backward compatibility with other version 1.x DTDs, -->
<!-- there are quite a few deprecated entries here. The documentation    -->
<!-- does not mention these deprecated entries. -->

<!-- The model element is deprecated.  Use entity instead. -->
<!ELEMENT model (class | configure | deleteEntity | deletePort |
		deleteRelation | director | display | doc | entity | group | import |
                input | link | property | relation | rename | rendition |
		unlink)*>
<!ATTLIST model name CDATA #REQUIRED
                class CDATA #IMPLIED>

<!ELEMENT class (class | configure | deleteEntity | deletePort |
		 deleteRelation | director | display | doc |
                 entity | group | import | input | link | port |
                 property | relation | rename | rendition | unlink)*>
<!ATTLIST class name CDATA #REQUIRED
                extends CDATA #IMPLIED
		source CDATA #IMPLIED>

<!ELEMENT configure (#PCDATA)>
<!ATTLIST configure source CDATA #IMPLIED>

<!ELEMENT deleteEntity EMPTY>
<!ATTLIST deleteEntity name CDATA #REQUIRED>

<!ELEMENT deletePort EMPTY>
<!ATTLIST deletePort name CDATA #REQUIRED>

<!ELEMENT deleteProperty EMPTY>
<!ATTLIST deleteProperty name CDATA #REQUIRED>

<!ELEMENT deleteRelation EMPTY>
<!ATTLIST deleteRelation name CDATA #REQUIRED>

<!-- NOTE: deprecated.  Use property instead. -->
<!ELEMENT director (configure | doc | property)*>
<!ATTLIST director name CDATA "director"
                   class CDATA #REQUIRED>

<!ELEMENT display EMPTY>
<!ATTLIST display name CDATA #REQUIRED>

<!ELEMENT doc (#PCDATA)>
<!ATTLIST doc name CDATA #IMPLIED>

<!ELEMENT entity (class | configure | deleteEntity | deletePort |
		  deleteRelation | director | display | doc |
                  entity | group | import | input | link | port |
                  property | relation | rename | rendition | unlink)*>
<!ATTLIST entity name CDATA #REQUIRED
                 class CDATA #IMPLIED
		 source CDATA #IMPLIED>

<!ELEMENT group ANY>
<!ATTLIST group name CDATA #IMPLIED>

<!-- The import element is deprecated.  Use the source attribute instead. -->
<!ELEMENT import EMPTY>
<!ATTLIST import source CDATA #REQUIRED
                 base CDATA #IMPLIED>

<!-- The base attribute is deprecated. -->
<!ELEMENT input EMPTY>
<!ATTLIST input source CDATA #REQUIRED
                base CDATA #IMPLIED>

<!ELEMENT link EMPTY>
<!ATTLIST link insertAt CDATA #IMPLIED
               insertInsideAt CDATA #IMPLIED
               port CDATA #REQUIRED
               relation CDATA #IMPLIED
               vertex CDATA #IMPLIED>

<!-- Deprecated.  Use a property instead. -->
<!ELEMENT location EMPTY>
<!ATTLIST location value CDATA #REQUIRED>

<!ELEMENT port (configure | display | doc | property | rename)*>
<!ATTLIST port class CDATA #IMPLIED
               name CDATA #REQUIRED>

<!ELEMENT property (configure | display | doc | property | rename)*>
<!ATTLIST property class CDATA #IMPLIED
                    name CDATA #REQUIRED
                    value CDATA #IMPLIED>

<!ELEMENT relation (configure | display | doc | property | rename | vertex)*>
<!ATTLIST relation name CDATA #REQUIRED
                   class CDATA #IMPLIED>

<!ELEMENT rename EMPTY>
<!ATTLIST rename name CDATA #REQUIRED>

<!-- Deprecated.  Use a property instead. -->
<!ELEMENT rendition (configure | location | property)*>
<!ATTLIST rendition class CDATA #REQUIRED>

<!ELEMENT unlink EMPTY>
<!ATTLIST unlink index CDATA #IMPLIED
                 insideIndex CDATA #IMPLIED
                 port CDATA #REQUIRED
                 relation CDATA #IMPLIED>

<!ELEMENT vertex (configure | display | doc | location | property | rename)*>
<!ATTLIST vertex name CDATA #REQUIRED
                 pathTo CDATA #IMPLIED
                 value CDATA #IMPLIED>

=== ptII/ptII/ptolemy/actor/lib/test/auto/TimedSinewave.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="TimedSinewave" class="ptolemy.actor.TypedCompositeActor">
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="8.1.devel">
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={231, 357, 813, 510}, maximized=false}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[600, 400]">
    </property>
    <property name="DE Director" class="ptolemy.domains.de.kernel.DEDirector">
        <property name="startTime" class="ptolemy.data.expr.Parameter" value="0.0">
        </property>
        <property name="stopTime" class="ptolemy.data.expr.Parameter" value="1.0">
        </property>
        <property name="stopWhenQueueIsEmpty" class="ptolemy.data.expr.Parameter" value="true">
        </property>
        <property name="synchronizeToRealTime" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="isCQAdaptive" class="ptolemy.data.expr.Parameter" value="true">
        </property>
        <property name="minBinCount" class="ptolemy.data.expr.Parameter" value="2">
        </property>
        <property name="binCountFactor" class="ptolemy.data.expr.Parameter" value="2">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="85.0, 45.0">
        </property>
    </property>
    <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.0">
    </property>
    <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{300.0, 200.0}">
    </property>
    <entity name="TimedSinewave" class="ptolemy.actor.lib.TriggeredSinewave">
        <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="2.1-devel-2">
        </property>
        <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[624, 450]">
        </property>
        <property name="_vergilLocation" class="ptolemy.actor.gui.LocationAttribute" value="[92, 102]">
        </property>
        <property name="magnitude" class="ptolemy.data.expr.Parameter" value="1.0">
        </property>
        <property name="frequency" class="ptolemy.actor.parameters.PortParameter" value="1.0">
            <property name="_iconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
                <configure>
      <svg>
	<polyline points="-15,-15, -3,-5, -16,5" style="stroke:black"></polyline>
      </svg>
    </configure>
            </property>
            <property name="_smallIconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
                <configure>
      <svg>
        <text x="20" style="font-size:14; font-family:SansSerif; fill:black" y="20">-P-</text>
      </svg>
    </configure>
            </property>
            <property name="_location" class="ptolemy.kernel.util.Location" value="45.0, 30.0">
            </property>
        </property>
        <property name="annotation" class="ptolemy.kernel.util.Attribute">
            <property name="_iconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
                <configure><svg><text x="20" y="20" style="font-size:14; font-family:SansSerif; fill:blue">Frequency is in Hz, or cycles/second, assuming time is in seconds.</text></svg></configure>
            </property>
            <property name="_smallIconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
                <configure>
      <svg>
        <text x="20" style="font-size:14; font-family:SansSerif; fill:blue" y="20">-A-</text>
      </svg>
    </configure>
            </property>
            <property name="_location" class="ptolemy.kernel.util.Location" value="120.0, 10.0">
            </property>
        </property>
        <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={135, 187, 839, 559}}">
        </property>
        <property name="phase" class="ptolemy.actor.parameters.PortParameter" value="0.0">
            <property name="_iconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
                <configure>
      <svg>
	<polyline points="-15,-15, -3,-5, -16,5" style="stroke:black"></polyline>
      </svg>
    </configure>
            </property>
            <property name="_smallIconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
                <configure>
      <svg>
        <text x="20" style="font-size:14; font-family:SansSerif; fill:black" y="20">-P-</text>
      </svg>
    </configure>
            </property>
            <property name="_location" class="ptolemy.kernel.util.Location" value="45.0, 70.0">
            </property>
        </property>
        <property name="SDF Director" class="ptolemy.domains.sdf.kernel.SDFDirector">
            <property name="iterations" class="ptolemy.data.expr.Parameter" value="0">
            </property>
            <property name="vectorizationFactor" class="ptolemy.data.expr.Parameter" value="1">
            </property>
            <property name="allowDisconnectedGraphs" class="ptolemy.data.expr.Parameter" value="false">
            </property>
            <property name="_location" class="ptolemy.kernel.util.Location" value="535.0, 75.0">
            </property>
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[190.0, 135.0]">
        </property>
    </entity>
    <entity name="Clock" class="ptolemy.actor.lib.Clock">
        <property name="period" class="ptolemy.actor.parameters.PortParameter" value="0.01">
        </property>
        <property name="offsets" class="ptolemy.data.expr.Parameter" value="{0.0}">
        </property>
        <property name="values" class="ptolemy.data.expr.Parameter" value="{1}">
        </property>
        <property name="numberOfCycles" class="ptolemy.data.expr.Parameter" value="-1">
        </property>
        <doc>Create a generalized square wave</doc>
        <property name="_location" class="ptolemy.kernel.util.Location" value="35.0, 125.0">
        </property>
    </entity>
    <entity name="CurrentTime" class="ptolemy.actor.lib.CurrentTime">
        <doc>Output the current time.</doc>
        <property name="_location" class="ptolemy.kernel.util.Location" value="95.0, 125.0">
        </property>
    </entity>
    <entity name="NonStrictTest" class="ptolemy.actor.lib.NonStrictTest">
        <property name="correctValues" class="ptolemy.data.expr.Parameter" value="{0.0, 6.2831848937626E-4, 0.002513271477, 0.0056548366384, 0.0100529271567, 0.0157073173118, 0.0226175383167, 0.0307827444258, 0.040201549363, 0.0508718331578, 0.0627905195293, 0.0759533240329, 0.0903544732799, 0.1059863956605, 0.1228393841472, 0.1409012319376, 0.1601568419022, 0.180587811053, 0.2021719915308, 0.2248830299327, 0.2486898871649, 0.2735563414121, 0.2994404772637, 0.3262941645261, 0.3540625307865, 0.3826834323651, 0.4120869289054, 0.4421947675002, 0.4729198829282, 0.504165921281, 0.535826794979, 0.5677862779101, 0.5999176501511, 0.632083402456, 0.6641350113835, 0.6959127965923, 0.7272458724244, 0.7579522064125, 0.7878387977665, 0.8167019891868, 0.844327925502, 0.8704931726011, 0.8949655099049, 0.9175049091638, 0.9378647116487, 0.9557930147983, 0.9710342780541, 0.9833311559394, 0.9924265643877, 0.9980659838701, 1.0, 0.9979870789813, 0.9917965715056, 0.9812119344932, 0.9660341554135, 0.9460853588275, 0.9212125692973, 0.8912915989357, 0.8562310216845, 0.8159761899698, 0.7705132427758, 0.7198730475073, 0.6641350113835, 0.6034306916726, 0.5379471279848, 0.4679298142606, 0.393685223227, 0.3155827921356, 0.2340562757751, 0.1496043712966, 0.0627905195293, -0.0257582105425, -0.1153532434083, -0.2052477076587, -0.2946408096143, -0.3826834323651, -0.4684850081806, -0.5511216948365, -0.6296458659693, -0.7030969021232, -0.7705132427758, -0.8309456304889, -0.8834714466863, -0.9272100047811, -0.9613386309271, -0.9851093261548, -0.9978657667669, -0.9990603634586, -0.9882710646188, -0.9652175567334, -0.9297764858882, -0.881995300294, -0.8221042958191, -0.7505264360367, -0.6678845165921, -0.5750052520433, -0.4729198829282, -0.3628609327076, -0.2462547893026, -0.1247098448141}">
        </property>
        <property name="tolerance" class="ptolemy.data.expr.Parameter" value="1.0E-9">
        </property>
        <property name="trainingMode" class="ptolemy.actor.parameters.SharedParameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="305.0, 125.0">
        </property>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
    </entity>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
        <property name="width" class="ptolemy.data.expr.Parameter" value="1">
        </property>
    </relation>
    <relation name="relation3" class="ptolemy.actor.TypedIORelation">
        <property name="width" class="ptolemy.data.expr.Parameter" value="1">
        </property>
    </relation>
    <relation name="relation2" class="ptolemy.actor.TypedIORelation">
        <property name="width" class="ptolemy.data.expr.Parameter" value="1">
        </property>
    </relation>
    <link port="TimedSinewave.frequency" relation="relation3"/>
    <link port="TimedSinewave.output" relation="relation2"/>
    <link port="Clock.output" relation="relation"/>
    <link port="CurrentTime.output" relation="relation3"/>
    <link port="CurrentTime.trigger" relation="relation"/>
    <link port="NonStrictTest.input" relation="relation2"/>
</entity>

=== ptII/ptII/ptolemy/codegen/java/actor/lib/test/auto/2Ramps.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="SDFCodegen1" class="ptolemy.actor.TypedCompositeActor">
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="8.1.devel">
    </property>
    <property name="SDF Director" class="ptolemy.domains.sdf.kernel.SDFDirector">
        <property name="iterations" class="ptolemy.data.expr.Parameter" value="10">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="{110.0, 115.0}">
        </property>
    </property>
    <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.9980569503279">
    </property>
    <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{355.5400390624999, 279.8319747681792}">
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={34, 22, 1406, 878}, maximized=true}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[1193, 771]">
    </property>
    <property name="JavaCodeGenerator" class="ptolemy.codegen.java.kernel.JavaCodeGenerator">
        <property name="_location" class="ptolemy.kernel.util.Location" value="{115.0, 275.0}">
        </property>
    </property>
    <entity name="Ramp" class="ptolemy.actor.lib.Ramp">
        <property name="init" class="ptolemy.data.expr.Parameter" value="1.2">
        </property>
        <doc>Create a sequence of tokens with increasing value</doc>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[275.0, 185.0]">
        </property>
    </entity>
    <entity name="CompositeActor" class="ptolemy.actor.TypedCompositeActor">
        <property name="_location" class="ptolemy.kernel.util.Location" value="{415, 220}">
        </property>
        <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={313, 196, 813, 507}, maximized=false}">
        </property>
        <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[600, 400]">
        </property>
        <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.0">
        </property>
        <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{300.0, 200.0}">
        </property>
        <port name="out" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
            <property name="_location" class="ptolemy.kernel.util.Location" value="{770.0, 235.0}">
            </property>
        </port>
        <port name="port" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
            <property name="_location" class="ptolemy.kernel.util.Location" value="{90.0, 210.0}">
            </property>
            <property name="width" class="ptolemy.data.expr.Parameter" value="-1">
            </property>
        </port>
        <entity name="AddSubtract" class="ptolemy.actor.lib.AddSubtract">
            <property name="_location" class="ptolemy.kernel.util.Location" value="{395.0, 225.0}">
            </property>
        </entity>
        <entity name="Scale" class="ptolemy.actor.lib.Scale">
            <property name="factor" class="ptolemy.data.expr.Parameter" value="3">
            </property>
            <property name="_location" class="ptolemy.kernel.util.Location" value="{265.0, 260.0}">
            </property>
            <property name="_icon" class="ptolemy.vergil.icon.AttributeValueIcon">
                <property name="attributeName" class="ptolemy.kernel.util.StringAttribute" value="factor">
                </property>
            </property>
        </entity>
        <entity name="ElementsToArray" class="ptolemy.actor.lib.ElementsToArray">
            <property name="_location" class="ptolemy.kernel.util.Location" value="{495.0, 235.0}">
            </property>
        </entity>
        <entity name="AddSubtract2" class="ptolemy.actor.lib.AddSubtract">
            <property name="_location" class="ptolemy.kernel.util.Location" value="{405.0, 315.0}">
            </property>
        </entity>
        <entity name="Scale2" class="ptolemy.actor.lib.Scale">
            <property name="factor" class="ptolemy.data.expr.Parameter" value="5">
            </property>
            <property name="_location" class="ptolemy.kernel.util.Location" value="{275.0, 335.0}">
            </property>
            <property name="_icon" class="ptolemy.vergil.icon.AttributeValueIcon">
                <property name="attributeName" class="ptolemy.kernel.util.StringAttribute" value="factor">
                </property>
            </property>
        </entity>
        <entity name="AddSubtract3" class="ptolemy.actor.lib.AddSubtract">
            <property name="_location" class="ptolemy.kernel.util.Location" value="{415.0, 370.0}">
            </property>
        </entity>
        <entity name="Scale3" class="ptolemy.actor.lib.Scale">
            <property name="factor" class="ptolemy.data.expr.Parameter" value="4">
            </property>
            <property name="_location" class="ptolemy.kernel.util.Location" value="{265.0, 415.0}">
            </property>
            <property name="_icon" class="ptolemy.vergil.icon.AttributeValueIcon">
                <property name="attributeName" class="ptolemy.kernel.util.StringAttribute" value="factor">
                </property>
            </property>
        </entity>
        <relation name="relation" class="ptolemy.actor.TypedIORelation">
            <property name="width" class="ptolemy.data.expr.Parameter" value="-1">
                <property name="_editorFactory" class="ptolemy.kernel.util.Attribute">
                </property>
            </property>
            <vertex name="vertex1" value="{185.0, 210.0}">
            </vertex>
        </relation>
        <relation name="relation2" class="ptolemy.actor.TypedIORelation">
        </relation>
        <relation name="relation3" class="ptolemy.actor.TypedIORelation">
        </relation>
        <relation name="relation4" class="ptolemy.actor.TypedIORelation">
        </relation>
        <relation name="relation5" class="ptolemy.actor.TypedIORelation">
        </relation>
        <relation name="relation6" class="ptolemy.actor.TypedIORelation">
        </relation>
        <relation name="relation7" class="ptolemy.actor.TypedIORelation">
        </relation>
        <relation name="relation8" class="ptolemy.actor.TypedIORelation">
        </relation>
        <link port="out" relation="relation6"/>
        <link port="port" relation="relation"/>
        <link port="AddSubtract.plus" relation="relation"/>
        <link port="AddSubtract.plus" relation="relation2"/>
        <link port="AddSubtract.output" relation="relation3"/>
        <link port="Scale.input" relation="relation"/>
        <link port="Scale.output" relation="relation2"/>
        <link port="ElementsToArray.input" relation="relation3"/>
        <link port="ElementsToArray.input" relation="relation5"/>
        <link port="ElementsToArray.input" relation="relation8"/>
        <link port="ElementsToArray.output" relation="relation6"/>
        <link port="AddSubtract2.plus" relation="relation4"/>
        <link port="AddSubtract2.plus" relation="relation"/>
        <link port="AddSubtract2.output" relation="relation5"/>
        <link port="Scale2.input" relation="relation"/>
        <link port="Scale2.output" relation="relation4"/>
        <link port="AddSubtract3.plus" relation="relation7"/>
        <link port="AddSubtract3.output" relation="relation8"/>
        <link port="Scale3.input" relation="relation"/>
        <link port="Scale3.output" relation="relation7"/>
    </entity>
    <entity name="Ramp2" class="ptolemy.actor.lib.Ramp">
        <property name="init" class="ptolemy.data.expr.Parameter" value="1.3">
        </property>
        <property name="step" class="ptolemy.actor.parameters.PortParameter" value="2">
        </property>
        <doc>Create a sequence of tokens with increasing value</doc>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[277.5390625, 260.78125]">
        </property>
    </entity>
    <entity name="Test" class="ptolemy.actor.lib.Test">
        <property name="correctValues" class="ptolemy.data.expr.Parameter" value="{{{4.8, 7.2, 4.8}}, {{8.8, 13.2, 8.8}}, {{12.8, 19.2, 12.8}}, {{16.8, 25.2, 16.8}}, {{20.8, 31.2, 20.8}}, {{24.8, 37.2, 24.8}}, {{28.8, 43.2, 28.8}}, {{32.8, 49.2, 32.8}}, {{36.8, 55.2, 36.8}}, {{40.8, 61.2, 40.8}}}">
        </property>
        <property name="trainingMode" class="ptolemy.actor.parameters.SharedParameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[520.0, 220.0]">
        </property>
    </entity>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation2" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation3" class="ptolemy.actor.TypedIORelation">
    </relation>
    <link port="Ramp.output" relation="relation"/>
    <link port="CompositeActor.out" relation="relation3"/>
    <link port="CompositeActor.port" relation="relation"/>
    <link port="CompositeActor.port" relation="relation2"/>
    <link port="Ramp2.output" relation="relation2"/>
    <link port="Test.input" relation="relation3"/>
</entity>

=== ptII/ptII/ptolemy/actor/lib/jai/test/auto/JAIBorder.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="JAIBorder" class="ptolemy.actor.TypedCompositeActor">
    <property name="SDF Director" class="ptolemy.domains.sdf.kernel.SDFDirector">
        <property name="Scheduler" class="ptolemy.domains.sdf.kernel.SDFScheduler">
        </property>
        <property name="allowDisconnectedGraphs" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="iterations" class="ptolemy.data.expr.Parameter" value="1">
        </property>
        <property name="vectorizationFactor" class="ptolemy.data.expr.Parameter" value="1">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="135.0, 50.0">
        </property>
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={232, 257, 815, 509}}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[600, 400]">
    </property>
    <property name="annotation" class="ptolemy.kernel.util.Attribute">
        <property name="_hideName" class="ptolemy.kernel.util.SingletonAttribute">
        </property>
        <property name="_iconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
            <configure><svg><text x="20" y="20" style="font-size:14; font-family:SansSerif; fill:blue">Adds a black border of 10 pixels
on all sides of the image.</text></svg></configure>
        </property>
        <property name="_smallIconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
            <configure>
      <svg>
        <text x="20" style="font-size:14; font-family:SansSerif; fill:blue" y="20">-A-</text>
      </svg>
    </configure>
        </property>
        <property name="_controllerFactory" class="ptolemy.vergil.basic.NodeControllerFactory">
        </property>
        <property name="_editorFactory" class="ptolemy.vergil.toolbox.AnnotationEditorFactory">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="70.0, 270.0">
        </property>
    </property>
    <entity name="JAIBorder" class="ptolemy.actor.lib.jai.JAIBorder">
        <property name="leftPadding" class="ptolemy.data.expr.Parameter" value="10">
        </property>
        <property name="rightPadding" class="ptolemy.data.expr.Parameter" value="10">
        </property>
        <property name="topPadding" class="ptolemy.data.expr.Parameter" value="10">
        </property>
        <property name="bottomPadding" class="ptolemy.data.expr.Parameter" value="10">
        </property>
        <property name="borderType" class="ptolemy.kernel.util.StringAttribute" value="Zero">
            <property name="style" class="ptolemy.actor.gui.style.ChoiceStyle">
                <property name="Constant" class="ptolemy.kernel.util.StringAttribute" value="Constant">
                </property>
                <property name="Copy" class="ptolemy.kernel.util.StringAttribute" value="Copy">
                </property>
                <property name="Reflect" class="ptolemy.kernel.util.StringAttribute" value="Reflect">
                </property>
                <property name="Wrap" class="ptolemy.kernel.util.StringAttribute" value="Wrap">
                </property>
                <property name="Zero" class="ptolemy.kernel.util.StringAttribute" value="Zero">
                </property>
            </property>
        </property>
        <property name="constants" class="ptolemy.data.expr.Parameter" value="{0.0}">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="205.0, 205.0">
        </property>
        <port name="input" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
        </port>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
    </entity>
    <entity name="JAIImageReader" class="ptolemy.actor.lib.jai.JAIImageReader">
        <property name="fileOrURL" class="ptolemy.data.expr.FileParameter" value="$CLASSPATH/doc/img/PtolemyII.jpg">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="90.0, 170.0">
        </property>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
        <port name="trigger" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <entity name="ImageDisplay" class="ptolemy.actor.lib.image.ImageDisplay">
        <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={266, 190, 748, 644}}">
        </property>
        <property name="_paneSize" class="ptolemy.actor.gui.SizeAttribute" value="[740, 596]">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="335.0, 240.0">
        </property>
        <port name="input" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation2" class="ptolemy.actor.TypedIORelation">
    </relation>
    <link port="JAIBorder.input" relation="relation"/>
    <link port="JAIBorder.output" relation="relation2"/>
    <link port="JAIImageReader.output" relation="relation"/>
    <link port="ImageDisplay.input" relation="relation2"/>
</entity>
