=== ptII/ptII/ptolemy/moml/MoML_1.dtd
<!-- MoML DTD Version 1.4, UC Berkeley -->
<!-- $Id$ -->
<!-- If you update this file, please also update:  -->
<!--    ptweb/xml/dtd/MoML_1.dtd, -->
<!--    ptII/doc/design/src/MoML.fm, -->
<!--    the static field MoML_DTD_1 in MoMLParser.java. -->
<!-- The top-level element can be either model or class. -->
<!-- NOTE: To ensure backward compatibility with other version 1.x DTDs, -->
<!-- there are quite a few deprecated entries here. The documentation    -->
<!-- does not mention these deprecated entries. -->

<!-- The model element is deprecated.  Use entity instead. -->
<!ELEMENT model (class | configure | deleteEntity | deletePort |
		deleteRelation | director | display | doc | entity | group | import |
                input | link | property | relation | rename | rendition |
		unlink)*>
<!ATTLIST model name CDATA #REQUIRED
                class CDATA #IMPLIED>

<!ELEMENT class (class | configure | deleteEntity | deletePort |
		 deleteRelation | director | display | doc |
                 entity | group | import | input | link | port |
                 property | relation | rename | rendition | unlink)*>
<!ATTLIST class name CDATA #REQUIRED
                extends CDATA #IMPLIED
		source CDATA #IMPLIED>

<!ELEMENT configure (#PCDATA)>
<!ATTLIST configure source CDATA #IMPLIED>

<!ELEMENT deleteEntity EMPTY>
<!ATTLIST deleteEntity name CDATA #REQUIRED>

<!ELEMENT deletePort EMPTY>
<!ATTLIST deletePort name CDATA #REQUIRED>

<!ELEMENT deleteProperty EMPTY>
<!ATTLIST deleteProperty name CDATA #REQUIRED>

<!ELEMENT deleteRelation EMPTY>
<!ATTLIST deleteRelation name CDATA #REQUIRED>

<!-- NOTE: deprecated.  Use property instead. -->
<!ELEMENT director (configure | doc | property)*>
<!ATTLIST director name CDATA "director"
                   class CDATA #REQUIRED>

<!ELEMENT display EMPTY>
<!ATTLIST display name CDATA #REQUIRED>

<!ELEMENT doc (#PCDATA)>
<!ATTLIST doc name CDATA #IMPLIED>

<!ELEMENT entity (class | configure | deleteEntity | deletePort |
		  deleteRelation | director | display | doc |
                  entity | group | import | input | link | port |
                  property | relation | rename | rendition | unlink)*>
<!ATTLIST entity name CDATA #REQUIRED
                 class CDATA #IMPLIED
		 source CDATA #IMPLIED>

<!ELEMENT group ANY>
<!ATTLIST group name CDATA #IMPLIED>

<!-- The import element is deprecated.  Use the source attribute instead. -->
<!ELEMENT import EMPTY>
<!ATTLIST import source CDATA #REQUIRED
                 base CDATA #IMPLIED>

<!-- The base attribute is deprecated. -->
<!ELEMENT input EMPTY>
<!ATTLIST input source CDATA #REQUIRED
                base CDATA #IMPLIED>

<!ELEMENT link EMPTY>
<!ATTLIST link insertAt CDATA #IMPLIED
               insertInsideAt CDATA #IMPLIED
               port CDATA #REQUIRED
               relation CDATA #IMPLIED
               vertex CDATA #IMPLIED>

<!-- Deprecated.  Use a property instead. -->
<!ELEMENT location EMPTY>
<!ATTLIST location value CDATA #REQUIRED>

<!ELEMENT port (configure | display | doc | property | rename)*>
<!ATTLIST port class CDATA #IMPLIED
               name CDATA #REQUIRED>

<!ELEMENT property (configure | display | doc | property | rename)*>
<!ATTLIST property class CDATA #IMPLIED
                    name CDATA #REQUIRED
                    value CDATA #IMPLIED>

<!ELEMENT relation (configure | display | doc | property | rename | vertex)*>
<!ATTLIST relation name CDATA #REQUIRED
                   class CDATA #IMPLIED>

<!ELEMENT rename EMPTY>
<!ATTLIST rename name CDATA #REQUIRED>

<!-- Deprecated.  Use a property instead. -->
<!ELEMENT rendition (configure | location | property)*>
<!ATTLIST rendition class CDATA #REQUIRED>

<!ELEMENT unlink EMPTY>
<!ATTLIST unlink index CDATA #IMPLIED
                 insideIndex CDATA #IMPLIED
                 port CDATA #REQUIRED
                 relation CDATA #IMPLIED>

<!ELEMENT vertex (configure | display | doc | location | property | rename)*>
<!ATTLIST vertex name CDATA #REQUIRED
                 pathTo CDATA #IMPLIED
                 value CDATA #IMPLIED>

=== ptII/ptII/ptolemy/actor/lib/test/auto/filterTest1.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="filterTest1" class="ptolemy.actor.TypedCompositeActor">
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="4.1">
    </property>
    <property name="SDF Director" class="ptolemy.domains.sdf.kernel.SDFDirector">
        <property name="allowDisconnectedGraphs" class="ptolemy.data.expr.Parameter" value="true">
        </property>
        <property name="iterations" class="ptolemy.data.expr.Parameter" value="1">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[-125.0, -20.0]">
        </property>
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={22, 102, 956, 466}, maximized=false}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[741, 350]">
    </property>
    <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.0">
    </property>
    <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{154.2176846590909, 107.1146622474748}">
    </property>
    <property name="N" class="ptolemy.data.expr.Parameter" value="2">
        <property name="_icon" class="ptolemy.vergil.icon.ValueIcon">
            <property name="_color" class="ptolemy.actor.gui.ColorAttribute" value="{0.0, 0.0, 1.0, 1.0}">
            </property>
        </property>
        <property name="_smallIconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
            <configure>
      <svg>
        <text x="20" style="font-size:14; font-family:SansSerif; fill:blue" y="20">-P-</text>
      </svg>
    </configure>
        </property>
        <property name="_editorFactory" class="ptolemy.vergil.toolbox.VisibleParameterEditorFactory">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[15.0, -30.0]">
        </property>
    </property>
    <entity name="Const" class="ptolemy.actor.lib.Const">
        <property name="value" class="ptolemy.data.expr.Parameter" value="function(x:double)x&gt;=5?true:false">
        </property>
        <doc>Create a constant sequence</doc>
        <property name="_icon" class="ptolemy.vergil.icon.BoxedValueIcon">
            <property name="attributeName" class="ptolemy.kernel.util.StringAttribute" value="value">
            </property>
            <property name="displayWidth" class="ptolemy.data.expr.Parameter" value="40">
            </property>
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[-20.0, 45.0]">
        </property>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
            <property name="_cardinal" class="ptolemy.kernel.util.StringAttribute" value="EAST">
            </property>
        </port>
        <port name="trigger" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
            <property name="_cardinal" class="ptolemy.kernel.util.StringAttribute" value="WEST">
            </property>
        </port>
    </entity>
    <entity name="Expression2" class="ptolemy.actor.lib.Expression">
        <property name="expression" class="ptolemy.kernel.util.StringAttribute" value="filter(f,in, N)">
        </property>
        <property name="_icon" class="ptolemy.vergil.icon.BoxedValueIcon">
            <property name="attributeName" class="ptolemy.kernel.util.StringAttribute" value="expression">
            </property>
            <property name="displayWidth" class="ptolemy.data.expr.Parameter" value="60">
            </property>
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[225.0, 95.0]">
        </property>
        <port name="f" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
        </port>
        <port name="in" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="_type" class="ptolemy.actor.TypeAttribute" value="unknown">
            </property>
        </port>
    </entity>
    <entity name="Const2" class="ptolemy.actor.lib.Const">
        <property name="value" class="ptolemy.data.expr.Parameter" value="{10,2,13,4,7,24}">
        </property>
        <doc>Create a constant sequence</doc>
        <property name="_icon" class="ptolemy.vergil.icon.BoxedValueIcon">
            <property name="attributeName" class="ptolemy.kernel.util.StringAttribute" value="value">
            </property>
            <property name="displayWidth" class="ptolemy.data.expr.Parameter" value="40">
            </property>
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[-35.0, 140.0]">
        </property>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
            <property name="_cardinal" class="ptolemy.kernel.util.StringAttribute" value="EAST">
            </property>
        </port>
        <port name="trigger" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
            <property name="_cardinal" class="ptolemy.kernel.util.StringAttribute" value="WEST">
            </property>
        </port>
    </entity>
    <entity name="NonStrictTest" class="ptolemy.actor.lib.NonStrictTest">
        <property name="correctValues" class="ptolemy.data.expr.Parameter" value="{{10, 13}}">
        </property>
        <property name="trainingMode" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="{340.0, 60.0}">
        </property>
    </entity>
    <entity name="Expression" class="ptolemy.actor.lib.Expression">
        <property name="expression" class="ptolemy.kernel.util.StringAttribute" value="filter(f,in)">
        </property>
        <property name="_icon" class="ptolemy.vergil.icon.BoxedValueIcon">
            <property name="attributeName" class="ptolemy.kernel.util.StringAttribute" value="expression">
            </property>
            <property name="displayWidth" class="ptolemy.data.expr.Parameter" value="60">
            </property>
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[205.0, 170.0]">
        </property>
        <port name="f" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
        </port>
        <port name="in" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="_type" class="ptolemy.actor.TypeAttribute" value="unknown">
            </property>
        </port>
    </entity>
    <entity name="NonStrictTest2" class="ptolemy.actor.lib.NonStrictTest">
        <property name="correctValues" class="ptolemy.data.expr.Parameter" value="{{10, 13, 7, 24}}">
        </property>
        <property name="trainingMode" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="{340.0, 185.0}">
        </property>
    </entity>
    <relation name="relation3" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation4" class="ptolemy.actor.TypedIORelation">
        <vertex name="vertex1" value="[115.0, 45.0]">
        </vertex>
    </relation>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
        <vertex name="vertex1" value="{155.0, 105.0}">
        </vertex>
    </relation>
    <relation name="relation2" class="ptolemy.actor.TypedIORelation">
    </relation>
    <link port="Const.output" relation="relation4"/>
    <link port="Expression2.output" relation="relation3"/>
    <link port="Expression2.f" relation="relation4"/>
    <link port="Expression2.in" relation="relation"/>
    <link port="Const2.output" relation="relation"/>
    <link port="NonStrictTest.input" relation="relation3"/>
    <link port="Expression.output" relation="relation2"/>
    <link port="Expression.f" relation="relation4"/>
    <link port="Expression.in" relation="relation"/>
    <link port="NonStrictTest2.input" relation="relation2"/>
</entity>

=== ptII/ptII/ptolemy/actor/ptalon/test/auto/mapreduce.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="mapreduce" class="ptolemy.actor.TypedCompositeActor">
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="6.1.devel">
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={3, 25, 889, 551}, maximized=false}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[674, 435]">
    </property>
    <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="0.923406413797">
    </property>
    <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{256.4948120117186, 184.8343811035154}">
    </property>
    <property name="DE Director" class="ptolemy.domains.de.kernel.DEDirector">
        <property name="stopTime" class="ptolemy.data.expr.Parameter" value="Infinity">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[-10.0, -20.0]">
        </property>
    </property>
    <property name="Annotation" class="ptolemy.vergil.kernel.attributes.TextAttribute">
        <property name="text" class="ptolemy.kernel.util.StringAttribute" value="MapReduce is a Ptalon actor that models the Google MapReduce system.  It is used&#10;to perform distributed computation on a data set, based on user supplied methods&#10;called map and reduce.  This demo shows an example using word count.  To make &#10;the demo work, you need to set the fileNamePrefix parameter to a String&#10;that points this model to the file $PTII/ptolemy/actor/ptalon/demo/MapReduce/ReadTest.map, &#10;an input data set for this demo.  Be sure to leave off the &quot;.map&quot; &#10;at the end of the file name. The outputs will be stored in &#10;$PTII/ptolemy/actor/ptalon/demo/MapReduce/ReadTest0.red,&#10;$PTII/ptolemy/actor/ptalon/demo/MapReduce/ReadTest1.red, etc.  The files show the counts of&#10;various words in the input files.">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[-95.0, 20.0]">
        </property>
    </property>
    <property name="Annotation2" class="ptolemy.vergil.kernel.attributes.TextAttribute">
        <property name="textColor" class="ptolemy.actor.gui.ColorAttribute" value="{1.0,0.0,0.0,1.0}">
        </property>
        <property name="text" class="ptolemy.kernel.util.StringAttribute" value="To make your own map reduce system, extend ptolemy.actor.ptalon.lib.MapReduceAlgorithm&#10;and implement the map and reduce methods.  To create a new instance of this&#10;actor, drag out a new PtalonActor from Actors--&gt;HigherOrderActors and set&#10;the ptalonCodeLocation to ptolemy.actor.ptalon.demo.MapReduce.MapReduce.  Set the&#10;className parameter to the qualified class name of your class.  In the above&#10;example, it's &quot;ptolemy.actor.ptalon.lib.WordCount&quot;.  Create a file similar&#10;to ReadTest.map with the appropriate input keys and values. ReadTest.map&#10;explains how to do this.  Set the numberOfMachines parameter to whatever you like, &#10;and set the fileNamePrefix as above.">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[-95.0, 220.0]">
        </property>
    </property>
    <entity name="MapReduce" class="ptolemy.actor.ptalon.PtalonActor">
        <property name="_location" class="ptolemy.kernel.util.Location" value="[115.0, -10.0]">
        </property>
        <configure>
            <ptalon file="ptolemy.actor.ptalon.demo.MapReduce.MapReduce">
                <ptalonExpressionParameter name="fileNamePrefix" value="&quot;ReadTest&quot;"/>
                <ptalonExpressionParameter name="className" value="&quot;ptolemy.actor.ptalon.lib.WordCount&quot;"/>
                <ptalonExpressionParameter name="numberOfMachines" value="5"/>
            </ptalon>
        </configure>
    </entity>
    <entity name="Test" class="ptolemy.actor.lib.Test">
        <property name="correctValues" class="ptolemy.data.expr.Parameter" value="{&quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;, &quot;finished&quot;}">
        </property>
        <property name="trainingMode" class="ptolemy.actor.parameters.SharedParameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[298.61328125, -10.380859375]">
        </property>
    </entity>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
        <property name="width" class="ptolemy.data.expr.Parameter" value="1">
        </property>
    </relation>
    <link port="MapReduce.status" relation="relation"/>
    <link port="Test.input" relation="relation"/>
</entity>

=== ptII/ptII/ptolemy/apps/ia/behavioraltype/simpledomain/BOTTOM.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="BOTTOM" class="ptolemy.domains.fsm.kernel.InterfaceAutomaton">
    <property name="initialStateName" class="ptolemy.kernel.util.StringAttribute" value="0">
    </property>
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="3.1-devel">
    </property>
    <property name="_library" class="ptolemy.moml.LibraryAttribute">
        <configure>
            <entity name="state library" class="ptolemy.kernel.CompositeEntity"><entity name="state" class="ptolemy.domains.fsm.kernel.State"></entity></entity>
          </configure>
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[602, 398]">
    </property>
    <property name="_vergilLocation" class="ptolemy.actor.gui.LocationAttribute" value="[14, 31]">
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={105, 127, 817, 514}, maximized=false}">
    </property>
    <property name="annotation" class="ptolemy.vergil.kernel.attributes.TextAttribute">
        <property name="text" class="ptolemy.kernel.util.StringAttribute" value="BOTTOM">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="455.0, 180.0">
        </property>
    </property>
    <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.0">
    </property>
    <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{301.0, 199.0}">
    </property>
    <port name="fC" class="ptolemy.actor.TypedIOPort">
        <property name="output"/>
        <property name="_location" class="ptolemy.kernel.util.Location" value="500.0, 250.0">
        </property>
    </port>
    <port name="fCR" class="ptolemy.actor.TypedIOPort">
        <property name="input"/>
        <property name="_location" class="ptolemy.kernel.util.Location" value="502.75, 285.0">
        </property>
    </port>
    <port name="hT" class="ptolemy.actor.TypedIOPort">
        <property name="input"/>
        <property name="_location" class="ptolemy.kernel.util.Location" value="375.0, 275.0">
        </property>
    </port>
    <port name="hTT" class="ptolemy.actor.TypedIOPort">
        <property name="output"/>
        <property name="_location" class="ptolemy.kernel.util.Location" value="375.0, 310.0">
        </property>
    </port>
    <port name="hTF" class="ptolemy.actor.TypedIOPort">
        <property name="output"/>
        <property name="_location" class="ptolemy.kernel.util.Location" value="375.0, 345.0">
        </property>
    </port>
    <port name="g" class="ptolemy.actor.TypedIOPort">
        <property name="input"/>
        <property name="_location" class="ptolemy.kernel.util.Location" value="375.0, 200.0">
        </property>
    </port>
    <port name="t" class="ptolemy.actor.TypedIOPort">
        <property name="output"/>
        <property name="_location" class="ptolemy.kernel.util.Location" value="374.62500000000085, 232.5">
        </property>
    </port>
    <entity name="0" class="ptolemy.domains.fsm.kernel.State">
        <property name="_location" class="ptolemy.kernel.util.Location" value="434.3333333333338, 239.1666666666669">
        </property>
    </entity>
    <relation name="relation10" class="ptolemy.domains.fsm.kernel.InterfaceAutomatonTransition">
        <property name="guardExpression" class="ptolemy.kernel.util.StringAttribute" value="g_isPresent">
        </property>
        <property name="exitAngle" class="ptolemy.data.expr.Parameter" value="2.2113108171358835">
        </property>
        <property name="gamma" class="ptolemy.data.expr.Parameter" value="-0.03677613968757671">
        </property>
        <property name="reset" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="preemptive" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="label" class="ptolemy.kernel.util.StringAttribute" value="g?">
        </property>
    </relation>
    <relation name="relation11" class="ptolemy.domains.fsm.kernel.InterfaceAutomatonTransition">
        <property name="guardExpression" class="ptolemy.kernel.util.StringAttribute" value="hT_isPresent">
        </property>
        <property name="exitAngle" class="ptolemy.data.expr.Parameter" value="2.3828277731196734">
        </property>
        <property name="gamma" class="ptolemy.data.expr.Parameter" value="-0.009933035657177031">
        </property>
        <property name="reset" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="preemptive" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="label" class="ptolemy.kernel.util.StringAttribute" value="hT?">
        </property>
    </relation>
    <relation name="relation" class="ptolemy.domains.fsm.kernel.InterfaceAutomatonTransition">
        <property name="guardExpression" class="ptolemy.kernel.util.StringAttribute" value="fCR_isPresent">
        </property>
        <property name="exitAngle" class="ptolemy.data.expr.Parameter" value="1.9144898013332292">
        </property>
        <property name="gamma" class="ptolemy.data.expr.Parameter" value="0.0017860027711730404">
        </property>
        <property name="reset" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="preemptive" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="label" class="ptolemy.kernel.util.StringAttribute" value="fCR?">
        </property>
    </relation>
    <link port="0.incomingPort" relation="relation10"/>
    <link port="0.incomingPort" relation="relation11"/>
    <link port="0.incomingPort" relation="relation"/>
    <link port="0.outgoingPort" relation="relation10"/>
    <link port="0.outgoingPort" relation="relation11"/>
    <link port="0.outgoingPort" relation="relation"/>
</entity>

=== ptII/ptII/ptolemy/actor/lib/jai/test/auto/JAIImageReader.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="JAIImageReader" class="ptolemy.actor.TypedCompositeActor">
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={232, 257, 815, 509}}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[600, 400]">
    </property>
    <property name="SDF Director" class="ptolemy.domains.sdf.kernel.SDFDirector">
        <property name="Scheduler" class="ptolemy.domains.sdf.kernel.SDFScheduler">
        </property>
        <property name="allowDisconnectedGraphs" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="iterations" class="ptolemy.data.expr.Parameter" value="1">
        </property>
        <property name="vectorizationFactor" class="ptolemy.data.expr.Parameter" value="1">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="65.0, 55.0">
        </property>
    </property>
    <property name="annotation" class="ptolemy.kernel.util.Attribute">
        <property name="_hideName" class="ptolemy.kernel.util.SingletonAttribute">
        </property>
        <property name="_iconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
            <configure><svg><text x="20" y="20" style="font-size:14; font-family:SansSerif; fill:blue">Read an image and display it.</text></svg></configure>
        </property>
        <property name="_smallIconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
            <configure>
      <svg>
        <text x="20" style="font-size:14; font-family:SansSerif; fill:blue" y="20">-A-</text>
      </svg>
    </configure>
        </property>
        <property name="_controllerFactory" class="ptolemy.vergil.basic.NodeControllerFactory">
        </property>
        <property name="_editorFactory" class="ptolemy.vergil.toolbox.AnnotationEditorFactory">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="140.0, 220.0">
        </property>
    </property>
    <entity name="JAIImageReader" class="ptolemy.actor.lib.jai.JAIImageReader">
        <property name="fileOrURL" class="ptolemy.data.expr.FileParameter" value="$CLASSPATH/doc/img/PtolemyII.jpg">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="165.0, 150.0">
        </property>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
        <port name="trigger" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <entity name="ImageDisplay" class="ptolemy.actor.lib.image.ImageDisplay">
        <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={276, 200, 728, 624}}">
        </property>
        <property name="_paneSize" class="ptolemy.actor.gui.SizeAttribute" value="[720, 576]">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="280.0, 190.0">
        </property>
        <port name="input" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
    </relation>
    <link port="JAIImageReader.output" relation="relation"/>
    <link port="ImageDisplay.input" relation="relation"/>
</entity>
